minimum_pre_commit_version: '4.0.0'
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-illegal-windows-names

  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: commitlint --edit
        language: node
        stages: [commit-msg]
      - id: eslint
        name: eslint
        entry: eslint --
        language: node
        files: \.(vue|[cm]?[jt]sx?)$
