name: Qodo Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && !github.event.pull_request.draft) ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request &&
       contains(fromJson('["OWNER","COLLABORATOR","MEMBER"]'), github.event.comment.author_association) &&
       startsWith(github.event.comment.body, '/'))
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Qodo Review
        uses: qodo-ai/pr-agent@e639d10a4df023b90668ec35796c2457c5f5db8d  # main as of 2026-06-16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
